import { useEffect, useState } from 'react'
import { BookOpen, CalendarDays, ChevronRight, Clock3, GraduationCap, Lightbulb, LockKeyhole, LogOut, PlayCircle, Sparkles, UserRound } from 'lucide-react'
import { portalApi, type AttendanceRecord, type PublishedAssessmentResult, type StudentEnrolment, type StudentMe, type StudentSchedule as StudentScheduleData } from '../api/portalApi'
import { CommunityFeed } from './CommunityFeed'

export function StudentPortalView({ studentName, activeTab, onLogout }: { studentName: string; activeTab: string; onLogout: () => void }) {
  const [student, setStudent] = useState<StudentMe['data']>(null)
  const [enrolments, setEnrolments] = useState<StudentEnrolment[]>([])
  const [attendance, setAttendance] = useState<AttendanceRecord[]>([])
  const [results, setResults] = useState<PublishedAssessmentResult[]>([])
  const [schedule, setSchedule] = useState<StudentScheduleData>({ entries: [], due_dates: [] })
  const [loading, setLoading] = useState(true)
  useEffect(() => { Promise.all([portalApi.getStudentMe(), portalApi.getStudentEnrolments(), portalApi.getStudentAttendance(), portalApi.getStudentAssessmentResults(), portalApi.getStudentSchedule()]).then(([self, history, attendanceResponse, resultResponse, scheduleResponse]) => { setStudent(self.data); setEnrolments(history.data); setAttendance(attendanceResponse.data); setResults(resultResponse.data); setSchedule(scheduleResponse.data) }).finally(() => setLoading(false)) }, [])
  if (activeTab === 'home') return <CommunityFeed role="student" userName={student?.full_name ?? studentName} />
  if (loading) return <div className="record-page"><div className="app-skeleton large" /><div className="app-skeleton" /><div className="app-skeleton" /></div>
  if (activeTab === 'learn') return <StudentLearn student={student} enrolments={enrolments} attendance={attendance} results={results} />
  if (activeTab === 'quiz') return <StudentQuiz />
  if (activeTab === 'schedule') return <StudentSchedule schedule={schedule} />
  return <StudentMore student={student} fallbackName={studentName} onLogout={onLogout} />
}

function Title({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <header className="record-page-title"><p>{eyebrow}</p><h1>{title}</h1><span>{copy}</span></header> }

function StudentLearn({ student, enrolments, attendance, results }: { student: StudentMe['data']; enrolments: StudentEnrolment[]; attendance: AttendanceRecord[]; results: PublishedAssessmentResult[] }) {
  const current = enrolments.find((item) => item.status === 'active') ?? enrolments[0]
  const subjects = current?.subjects ?? []
  const counts = { present: attendance.filter((item) => item.status === 'present').length, late: attendance.filter((item) => item.status === 'late').length, absent: attendance.filter((item) => item.status === 'absent').length }
  return <div className="record-page"><Title eyebrow="My learning" title="Progress at a glance" copy={`${student?.class?.name ?? current?.class?.name ?? 'Current class'} · live enrolment, attendance, and published results`} /><section className="student-progress-banner"><span><small>Recorded attendance</small><strong>{attendance.length}</strong><em>{counts.present} present · {counts.late} late · {counts.absent} absent</em></span><CalendarDays /></section><div className="section-heading"><span><b>My subjects</b><small>{subjects.length} current subject{subjects.length === 1 ? '' : 's'}</small></span></div><div className="subject-list">{subjects.map((subject, index) => <button type="button" disabled key={`${subject.subject_id ?? index}-${subject.subject_name}`}><span className={`subject-mark mark-${index % 4}`}><BookOpen /></span><span><strong>{subject.subject_name}</strong><small>{subject.teacher_name ?? 'Teacher to be confirmed'}</small></span><span className="subject-score">Current<small>Enrolment</small></span><ChevronRight /></button>)}</div><div className="section-heading"><span><b>Published results</b><small>{results.length} result{results.length === 1 ? '' : 's'}</small></span></div>{results.map((result) => <article className="feedback-card" key={result.id}><Lightbulb /><div><strong>{result.subject} · {result.title}</strong><p>{result.score} / {result.max_score}{result.grade_label ? ` · ${result.grade_label}` : ''}</p>{result.teacher_comment && <small>{result.teacher_comment}</small>}</div></article>)}{results.length === 0 && <p className="quiet-empty">No assessment results have been published.</p>}</div>
}

function StudentQuiz() {
  return <div className="record-page"><Title eyebrow="Quiz" title="Test what you know" copy="Formal assignments and personal practice stay separate." /><div className="preview-label">Design preview · Quiz delivery is not connected</div><section className="quiz-callout"><span className="quiz-icon"><GraduationCap /></span><div><small>Example assignment</small><h2>Fractions checkpoint</h2><p>10 questions · Multiple choice · Example only</p><span className="status-label neutral">Preview</span></div><button type="button" disabled>Quiz coming later <ChevronRight /></button></section><div className="section-heading"><span><b>Assigned quizzes</b><small>Example formal school work</small></span></div><button type="button" className="quiz-row" disabled><span className="quiz-row-icon blue"><PlayCircle /></span><span><strong>Water cycle review</strong><small>Science · example result</small></span><span className="status-label neutral">Preview</span><ChevronRight /></button><button type="button" className="quiz-row" disabled><span className="quiz-row-icon amber"><Clock3 /></span><span><strong>Grammar: past tense</strong><small>English · example due date</small></span><span className="status-label neutral">Preview</span><ChevronRight /></button><div className="section-heading"><span><b>Practice quiz</b><small>Private · never part of formal grades</small></span></div><section className="practice-builder"><Sparkles /><h2>Build a personal practice</h2><p>Choose a subject, topic, difficulty, and question count. AI generation is not active.</p><div className="practice-options"><button type="button" disabled>Mathematics</button><button type="button" disabled>Science</button><button type="button" disabled>English</button></div><button type="button" className="secondary-action" disabled><LockKeyhole /> Practice generator coming later</button></section></div>
}

const dayNames = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
function StudentSchedule({ schedule }: { schedule: StudentScheduleData }) {
  const today = new Date().getDay()
  const [day, setDay] = useState(today === 0 ? 7 : today)
  const entries = schedule.entries.filter((entry) => entry.day_of_week === day)
  return <div className="record-page"><Title eyebrow="Schedule" title="Your school week" copy="Published classes and assessment due dates from MIS." /><div className="date-switcher"><button type="button" aria-label="Previous day" onClick={() => setDay(day === 1 ? 7 : day - 1)}>‹</button><span><strong>{dayNames[day - 1]}</strong><small>Published class schedule</small></span><button type="button" aria-label="Next day" onClick={() => setDay(day === 7 ? 1 : day + 1)}>›</button></div>{entries.length ? <section className="timeline">{entries.map((entry) => <ScheduleItem key={entry.id} time={entry.starts_at} title={entry.title} detail={[entry.teacher, entry.location, entry.ends_at].filter(Boolean).join(' · ')} />)}</section> : <p className="quiet-empty">No published classes for {dayNames[day - 1]}.</p>}<div className="section-heading"><span><b>Assessment due dates</b><small>{schedule.due_dates.length} published</small></span></div>{schedule.due_dates.map((item) => <div className="calendar-note" key={item.assessment_id}><CalendarDays /><span><strong>{item.subject} · {item.title}</strong><small>{new Date(item.due_at).toLocaleString()}</small></span></div>)}{schedule.due_dates.length === 0 && <p className="quiet-empty">No published assessment due dates.</p>}</div>
}
function ScheduleItem({ time, title, detail }: { time: string; title: string; detail: string }) { return <div className="timeline-row"><time>{time}</time><i /><span><strong>{title}</strong><small>{detail}</small></span></div> }

function StudentMore({ student, fallbackName, onLogout }: { student: StudentMe['data']; fallbackName: string; onLogout: () => void }) { const name = student?.full_name ?? fallbackName; return <div className="record-page"><Title eyebrow="Account" title="Profile and settings" copy="Your private student access." /><section className="profile-card"><span className="profile-avatar">{name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</span><h2>{name}</h2><p>{student?.student_no ?? 'Student account'} · {student?.class?.name ?? 'No class'}</p></section><section className="settings-list"><div><UserRound /><span><small>Role</small><strong>Student self-service</strong></span></div><button type="button" disabled><span><small>Notifications · coming later</small><strong>School and class updates</strong></span><ChevronRight /></button><button type="button" disabled><span><small>Privacy · coming later</small><strong>Community visibility information</strong></span><ChevronRight /></button></section><button type="button" className="logout-action" aria-label="Sign out" onClick={onLogout}><LogOut /><span><strong>Sign out</strong><small>End this session on this device</small></span></button></div> }
